name: CoreU
version: '1.0-SNAPSHOT'
main: me.udnek.coreu.CoreU
description: CoreU
api-version: '1.21.11'
bootstrapper: me.udnek.coreu.bootstrap.Bootstrap

horizon:
  mixins:
    - "coreu.mixins.json"
  load-datapack-entry: true

dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: true
      join-classpath: true
