name: CoreU
version: '${project.version}'
main: me.udnek.coreu.CoreU
api-version: '1.21.8'
depend: [ ProtocolLib ]
load: STARTUP
commands:
  helpu:
    description: "helpu"
    usage: "/helpu"
    aliases: [ coreu_help, ?, h ]
    permission-message: "You do not have permission to use this command"
  giveu:
    description: "giveu"
    usage: "/giveu <item>"
    aliases: [coreu_give]
    permission: coreu.admin
    permission-message: "You do not have permission to use this command"
  summonu:
    description: "summonu"
    usage: "/summonu <entity>"
    aliases: [coreu_summon]
    permission: coreu.admin
    permission-message: "You do not have permission to use this command"
  custom_entities:
      description: "custom_entities"
      usage: "/custom_entities"
      aliases: []
      permission: coreu.admin
      permission-message: "You do not have permission to use this command"
  resourcepacku:
    description: "resourcepacku"
    usage: "/resourcepacku <directory>"
    aliases: [ coreu_resourcepack ]
    permission: coreu.admin
    permission-message: "You do not have permission to use this command"
  attributeu:
      description: "attributeu"
      usage: "/attributeu <attribute>"
      aliases: [ coreu_attribute ]
      permission: coreu.admin
      permission-message: "You do not have permission to use this command"
  clear_attribute_modifiers:
      description: "cleat_attribute_modifiers"
      usage: "/cleat_attribute_modifiers"
      aliases: []
      permission: coreu.admin
      permission-message: "You do not have permission to use this command"
  set_blocku:
      description: "set_blocku"
      usage: "/set_blocku <block>"
      aliases: [coreu_set_block]
      permission: coreu.admin
      permission-message: "You do not have permission to use this command"
  custom_block_entities:
      description: "custom_block_entities"
      usage: "/custom_block_entities"
      aliases: []
      permission: coreu.admin
      permission-message: "You do not have permission to use this command"
  play_soundu:
      description: "play_soundu"
      usage: "/play_soundu <sound>"
      aliases: [coreu_play_sound]
      permission: coreu.admin
      permission-message: "You do not have permission to use this command"
  effectu:
      description: "effectu"
      usage: "/effectu <effect> [duration] [lvl]"
      aliases: [coreu_effect]
      permission: coreu.admin
      permission-message: "You do not have permission to use this command"
  mgu:
      description: "mgu"
      usage: "/mgu <start/stop/join/leave/debug/coordinate_want/execute> [gameId]"
      aliases: [coreu_minigame]
      permission: coreu.admin
      permission-message: "You do not have permission to use this command"
  inventory_inspection:
      description: "inventory_inspection"
      usage: "/inventory_inspection"
      aliases: [ ]
      permission: coreu.admin
      permission-message: "You do not have permission to use this command"
  reset_cooldown:
    description: "reset_cooldown"
    usage: "/reset_cooldown"
    aliases: [ cooldown_reset ]
    permission: coreu.admin
    permission-message: "You do not have permission to use this command"